### ISSUE TITLE
Pesquisar framework em NodeJs para desenvolvimento da API do projeto. 

### ISSUE THREAD

**Issue by viriatonova** [capaolab/vibes#1]
## Descrição

Precisamos pesquisar um framework baseado em NodeJs para desenvolver a API do projeto que seja de facil manuteção e que tenhoa suficiente documentação para bug tacking.  

Previamente penso que podemos começar a pesquisa comparando os seguintes frameworks: NestJS, Express e NextJS.

**Comment by Rodrigo-Dev123** [comment]
Pelo que eu pesquisei, eu vi que o NestJS tem o Express embutido nele e que ele já faz o que o Express faz então ele já é melhor do que o Express por ter mais utilidades, e também o NestJS além de ser popular, é de fácil manutenção e trabalha com tipagem e pode ver os erros que acontecem nele e sendo assim eu acho que ele é melhor para desenvolver a API.

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 ,

Você considerou o fato de poder fazer a api e o front em conjunto no NextJS ? Dê uma olhada nisso e veja se pode ser uma alternativa melhor. Lembrando que o framework que escolhemos é necessáriamente o que você vai "estudar" mais a fundo. 

Vou abrir um novo ticket para fazer um hello world da API, assim que tomar a decisão já pode implementar.

**Comment by Rodrigo-Dev123** [comment]
Se a gente for considerar o front-end então a melhor escolha seria o NextJS, porque pelo o que eu pesquisei o NestJS trabalha só no back-end.

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 ,

Seguindo nossa convesa vamos implementar o Express. vou fechar a issue
