### ISSUE TITLE
Fazer hello world da API. 

### ISSUE THREAD

**Issue by viriatonova** [capaolab/vibes#2]
## Descrição

Assim que decidirmos o framework a ser utilizado vamos fazer a implementação básica do API, seguido o modelo REST API. 

### Cenário

**Dado que :** Precisamos iniciar a API do projeto

**Quando :** Acessar a pasta api na seguite estrutura:
```text
.
└── Vides/
    ├── vibes_app/
    ├── vibes_api/
    ├── .gitignore
    └── readme.md
```

**Então :** Precisamos ver a frase `Hello World` apresentada na rota principal da API em uma JSON response

**Comment by Rodrigo-Dev123** [comment]
Eu fiz e já mandei um commit para a branch task.

**Comment by viriatonova** [comment]
Aqui o [pull request](https://github.com/capaolab/vibes/pull/3):
