### ISSUE TITLE
Implementar leitura de variáveis de ambiente

### ISSUE THREAD

**Issue by viriatonova** [capaolab/vibes#5]
## Descrição

Para evitara implementação de constantes `hardcoded` no projeto precisamos implementar a leitura de arquivo `.env`, onde iremos armazernar variáveis de ambiente.

## Cenário

**Dado que :** as variáveis de ambiente sejam armazenadas em um arquivo `env`
**Quando :** a executarmos a aplicação
**Então :** esperamos que essas variáveis sejam carregadas em constantes no arquivo `vibes_api/src/configs/settings.js`

**Comment by Rodrigo-Dev123** [comment]
* [New pull request](https://github.com/capaolab/vibes/pull/7)

**Description:**  added environment variables
